
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-api-gateway
  namespace: api 
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "dev.sample-api.127.0.0.1.sslip.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-api-vs
  namespace: api 
spec:
  hosts:
  - "dev.sample-api.127.0.0.1.sslip.io"
  gateways:
  - sample-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: sample-api-active
        port:
          number: 8080