apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sample-api-rollout.yaml
- sample-api-svc-active.yaml
- sample-api-svc-preview.yaml
- ingress-sample-api.yaml
- ingress-preview-sample-api.yaml
images:
- name: oscka/sample-api
  newTag: 0.0.2
