apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sample-api-svc.yaml
- sample-api-deployment.yaml
- ingress-sample-api.yaml

images:
- name: oscka/sample-api
  newTag: 0.0.14
